services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: book-order-sqlserver
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "Aliali123@"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:16-alpine
    container_name: book-order-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PostgrePassword123!
      POSTGRES_DB: catalogdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: book-order-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: book-order-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_tracing && rabbitmq-server"




volumes:
  sqlserver-data:
  postgres-data:
  redis-data:
  rabbitmq-data:
